### ISSUE TITLE
Using with headscale + nginx-proxy-manager

### ISSUE THREAD

**Issue by petre-c** [Wind4/tailscale-derper#1]
@Wind4, this was useful, thank you 🙂

Couple things:
- I'm setting this up on a Raspberry Pi (ARM64), with [headscale](https://github.com/juanfont/headscale), behind [Nginx-Proxy-Manager](https://github.com/NginxProxyManager/nginx-proxy-manager). Had to build from `Dockerfile` instead of using the pre-built image, which doesn't seem to have ARM support

```yml
services:
  derper:
    build: .
#    image: ghcr.io/wind4/tailscale-derper:main
    environment:
      - TS_SERVER=https://{headscale-server-url}
      - TS_AUTHKEY={authkey}
      - TS_EXTRA_ARGS=--hostname depr-01
      - DERP_DOMAIN={derp_domain}
      - DERP_ADDR=:80
      - DERP_VERIFY_CLIENTS=false
    networks:
      - external-network
    ports:
      - "3478:3478/udp"
    restart: unless-stopped

networks:
  external-network:
    external: true
```
- For some reason having `DERP_VERIFY_CLIENTS=true` didn't work for me with the reason: `client nodekey:{node-key} rejected: tailscaled version is too old (out of sync with derper binary)`. Maybe related to my using `headscale`. Setting it to `false` fixed it
- I forgot to enable `Websockets support` in nginx-proxy-manager, without which derper doesn't work

I'm just documenting my experience, there's nothing to do.

Have a good day!
